taxonomy = {'Analyze': ['Analyze', 'Audit', 'Blueprint', 'Breadboard', 'Break down', 'Characterize', 'Classify', 'Compare',
                        'Confirm', 'Contrast', 'Correlate', 'Detect', 'Diagnose', 'Diagram', 'Differentiate', 'Discriminate',
                        'Dissect', 'Distinguish', 'Document', 'Ensure', 'Examine', 'Explain', 'Explore', 'Figure out', 'File',
                        'Group', 'Identify', 'Illustrate', 'Infer', 'Interrupt', 'Validate', 'Verify', 'Integrate', 'Interface',
                        'Join', 'Lecture', 'Model', 'Modify', 'Network', 'Organize', 'Outline'],
            'Apply': ['Acquire', 'Adapt', 'Allocate', 'Alphabetize', 'Apply', 'Ascertain', 'Assign', 'Attain', 'Avoid', 'Back up',
                      'Calculate', 'Capture', 'Change', 'Classify', 'Complete', 'Compute', 'Construct', 'Customize', 'Demonstrate',
                      'Depreciate', 'Derive', 'Determine', 'Diminish', 'Discover', 'Draw', 'Employ', 'Examine', 'Exercise',
                      'Explore', 'Expose', 'Inventory', 'Investigate', 'Layout', 'Manage', 'Maximize', 'Minimize', 'Optimize',
                      'Order', 'Outline', 'Point out', 'Prioritize', 'Overhaul', 'Plan', 'Portray', 'Prepare', 'Prescribe',
                      'Produce', 'Program', 'Rearrange'],
            'Create': ['Abstract', 'Animate', 'Arrange', 'Assemble', 'Budget', 'Categorize', 'Code', 'Combine', 'Compile',
                       'Compose', 'Construct', 'Cope', 'Correspond', 'Create', 'Cultivate', 'Debug', 'Depict', 'Design', 'Develop',
                       'Devise', 'Dictate', 'Enhance', 'Explain', 'Facilitate', 'Format', 'Formulate', 'Generalize', 'Generate',
                       'Handle', 'Import'],
            'Evaluate': ['Appraise', 'Assess', 'Compare', 'Conclude', 'Contrast', 'Counsel', 'Criticize', 'Critique', 'Defend',
                         'Determine', 'Discriminate', 'Estimate', 'Evaluate', 'Explain', 'Grade', 'Hire', 'Interpret', 'Judge',
                         'Justify', 'Measure', 'Predict', 'Prescribe', 'Rank', 'Rate', 'Recommend', 'Release', 'Select',
                         'Summarize', 'Support', 'Test', 'Improve', 'Incorporate'],
            'Remember': ['Cite', 'Define', 'Describe', 'Draw', 'Enumerate', 'Identify', 'Index', 'Indicate', 'Label', 'List',
                         'Match', 'Meet', 'Name', 'Outline', 'Point', 'Quote', 'Read', 'Recall', 'Recite', 'Recognize', 'Record',
                         'Repeat', 'Reproduce', 'Review', 'Select', 'State', 'Study', 'Tabulate', 'Trace', 'Write', 'Interpret',
                         'Observe', 'Paraphrase', 'Picture graphically', 'Predict', 'Review', 'Rewrite', 'Subtract', 'Summarize',
                         'Translate', 'Visualize', 'Personalize', 'Plot', 'Practice', 'Predict', 'Prepare', 'Price', 'Process',
                         'Produce', 'Project', 'Provide', 'Relate', 'Round off', 'Sequence', 'Show', 'Simulate', 'Sketch', 'Solve',
                         'Subscribe', 'Tabulate', 'Transcribe', 'Translate', 'Use'],
            'Understand': ['Add', 'Approximate', 'Articulate', 'Associate', 'Characterize', 'Clarify', 'Classify', 'Compare',
                           'Compute', 'Contrast', 'Convert', 'Defend', 'Describe', 'Detail', 'Differentiate', 'Discuss',
                           'Distinguish', 'Elaborate', 'Estimate', 'Example', 'Explain', 'Express', 'Extend', 'Extrapolate',
                           'Factor', 'Generalize', 'Give', 'Infer', 'Interact', 'Interpolate', 'Express', 'Factor', 'Figure',
                           'Graph', 'Handle', 'Illustrate', 'Interconvert', 'Investigate', 'Manipulate', 'Modify', 'Operate',
                           'Proofread', 'Query', 'Relate', 'Select', 'Separate', 'Subdivide', 'Train', 'Transform', 'Reconstruct',
                           'Relate', 'Reorganize', 'Revise', 'Rewrite', 'Specify', 'Summarize']}
